syntax on
set number
set splitright
set splitbelow
set ttimeoutlen=50
let mapleader=";"

" ALE
let g:ale_fix_on_save = 1
let g:ale_python_auto_uv = 1
let g:ale_linters = {"python": ["ruff", "pyright", "pylint"]}
let g:ale_fixers = {"python": ["ruff_format", "isort"]}
